const GROUP_SIZE = 45;

function makeCategory(slug, label, items) {
  const unique = [...new Set(items.map((item) => item.trim()))];
  if (unique.length !== GROUP_SIZE) {
    throw new Error(`${slug} must have exactly ${GROUP_SIZE} unique items.`);
  }
  return { slug, label, items: unique };
}

function buildChunkedCategories(poolLabel, count, prefix, priority) {
  const out = [];
  for (let chunk = 0; chunk < count; chunk += 1) {
    const items = [];
    for (let i = 1; i <= GROUP_SIZE; i += 1) {
      items.push(`${prefix} ${chunk * GROUP_SIZE + i}`);
    }
    out.push(makeCategory(`${poolLabel}-${chunk + 1}`, `${poolLabel.replace(/-/g, " ")} ${chunk + 1}`, items));
  }
  return out.map((cat) => ({ ...cat, priority }));
}

function buildCategoryBank() {
  const explicit = [
    { ...makeCategory("pasta-types", "pasta types", [
      "spaghetti",
      "penne",
      "rigatoni",
      "fusilli",
      "farfalle",
      "linguine",
      "fettuccine",
      "ravioli",
      "tortellini",
      "gnocchi",
      "ziti",
      "macaroni",
      "cavatappi",
      "rotini",
      "bucatini",
      "orecchiette",
      "pappardelle",
      "lasagna",
      "tagliatelle",
      "vermicelli",
      "angel hair",
      "ditalini",
      "manicotti",
      "capellini",
      "gemelli",
      "mafaldine",
      "radiatori",
      "campanelle",
      "strozzapreti",
      "paccheri",
      "anelletti",
      "bigoli",
      "casarecce",
      "trofie",
      "malloreddus",
      "lumache",
      "fregola",
      "mezzi rigatoni",
      "spaghettini",
      "cellentani",
      "tubetti",
      "sedani",
      "filini",
      "orzo",
      "cannelloni"
    ]), priority: 1 },
    { ...makeCategory("spices-and-herbs", "spices and herbs", [
      "basil",
      "oregano",
      "thyme",
      "rosemary",
      "cumin",
      "turmeric",
      "paprika",
      "cinnamon",
      "nutmeg",
      "clove",
      "cardamom",
      "parsley",
      "dill",
      "sage",
      "tarragon",
      "sumac",
      "za'atar",
      "bay leaf",
      "fennel",
      "anise",
      "chives",
      "mint",
      "marjoram",
      "caraway",
      "coriander",
      "ginger",
      "allspice",
      "saffron",
      "vanilla",
      "sesame",
      "mustard seed",
      "celery seed",
      "fenugreek",
      "star anise",
      "lemongrass",
      "chili powder",
      "cayenne",
      "garlic powder",
      "onion powder",
      "smoked paprika",
      "herbes de provence",
      "lovage",
      "savory",
      "asafoetida",
      "nigella"
    ]), priority: 1 },
    { ...makeCategory("european-countries", "european countries", [
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Poland",
      "Austria",
      "Greece",
      "Ireland",
      "Iceland",
      "Romania",
      "Hungary",
      "Croatia",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Estonia",
      "Latvia",
      "Lithuania",
      "Switzerland",
      "Ukraine",
      "Albania",
      "Andorra",
      "Belarus",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Cyprus",
      "Czech Republic",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Montenegro",
      "North Macedonia",
      "San Marino",
      "Kosovo",
      "Liechtenstein",
      "Monaco",
      "Turkey",
      "Vatican City"
    ]), priority: 1 },
    { ...makeCategory("us-states", "us states", [
      "alabama",
      "alaska",
      "arizona",
      "arkansas",
      "california",
      "colorado",
      "connecticut",
      "delaware",
      "florida",
      "georgia",
      "hawaii",
      "idaho",
      "illinois",
      "indiana",
      "iowa",
      "kansas",
      "kentucky",
      "louisiana",
      "maine",
      "maryland",
      "massachusetts",
      "michigan",
      "minnesota",
      "mississippi",
      "missouri",
      "montana",
      "nebraska",
      "nevada",
      "new hampshire",
      "new jersey",
      "new mexico",
      "new york",
      "north carolina",
      "north dakota",
      "ohio",
      "oklahoma",
      "oregon",
      "pennsylvania",
      "rhode island",
      "south carolina",
      "south dakota",
      "tennessee",
      "texas",
      "utah",
      "vermont"
    ]), priority: 1 },
    { ...makeCategory("us-cities", "us cities", [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Boston",
      "El Paso",
      "Detroit",
      "Nashville",
      "Portland",
      "Memphis",
      "Oklahoma City",
      "Las Vegas",
      "Louisville",
      "Baltimore",
      "Milwaukee",
      "Albuquerque",
      "Tucson",
      "Fresno",
      "Sacramento",
      "Kansas City",
      "Mesa",
      "Atlanta",
      "Omaha",
      "Raleigh",
      "Miami",
      "Oakland",
      "Minneapolis",
      "Tulsa",
      "Cleveland",
      "Wichita",
      "Arlington"
    ]), priority: 1 },
    { ...makeCategory("office-items", "office items", [
      "printer",
      "stapler",
      "notebook",
      "pen",
      "pencil",
      "monitor",
      "keyboard",
      "mouse",
      "desk",
      "chair",
      "whiteboard",
      "calendar",
      "folder",
      "binder",
      "paper clips",
      "tape",
      "scissors",
      "highlighter",
      "envelope",
      "sticky notes",
      "scanner",
      "phone",
      "lamp",
      "filing cabinet",
      "push pins",
      "rubber bands",
      "clipboard",
      "hole punch",
      "label maker",
      "shredder",
      "desk pad",
      "mail tray",
      "eraser",
      "ruler",
      "extension cord",
      "surge protector",
      "dry erase marker",
      "bulletin board",
      "ink cartridge",
      "toner",
      "calculator",
      "mug",
      "paper ream",
      "lanyard",
      "name badge"
    ]), priority: 1 },
    { ...makeCategory("sci-fi-shows", "sci fi shows", [
      "The X-Files",
      "Doctor Who",
      "Black Mirror",
      "Battlestar Galactica",
      "The Twilight Zone",
      "Westworld",
      "Fringe",
      "Lost in Space",
      "The Expanse",
      "Firefly",
      "Severance",
      "Dark",
      "Foundation",
      "Silo",
      "Andor",
      "Star Trek",
      "Star Trek: Voyager",
      "Star Trek: Discovery",
      "Star Trek: Picard",
      "Raised by Wolves",
      "Orphan Black",
      "Sense8",
      "Heroes",
      "Torchwood",
      "Humans",
      "Altered Carbon",
      "Travelers",
      "Devs",
      "Halo",
      "Snowpiercer",
      "Continuum",
      "Farscape",
      "Eureka",
      "Quantum Leap",
      "Caprica",
      "Alien Nation",
      "Resident Alien",
      "Upload",
      "Beacon 23",
      "3 Body Problem",
      "The Peripheral",
      "Blake's 7",
      "Babylon 5",
      "Red Dwarf",
      "Lexx"
    ]), priority: 1 },
    { ...makeCategory("comic-artists", "comic artists", [
      "Jack Kirby",
      "Stan Lee",
      "Steve Ditko",
      "Jim Lee",
      "Frank Miller",
      "Alan Moore",
      "Neal Adams",
      "Todd McFarlane",
      "John Romita Sr.",
      "John Byrne",
      "Alex Ross",
      "George Perez",
      "Brian Bolland",
      "Rob Liefeld",
      "Dave Gibbons",
      "Joe Kubert",
      "Will Eisner",
      "Art Spiegelman",
      "Chris Claremont",
      "Walt Simonson",
      "Carmine Infantino",
      "Gil Kane",
      "Mike Mignola",
      "Moebius",
      "Osamu Tezuka",
      "Rumiko Takahashi",
      "Katsuhiro Otomo",
      "Harvey Kurtzman",
      "Charles Schulz",
      "Bill Watterson",
      "Jim Davis",
      "Al Capp",
      "Herge",
      "R. Crumb",
      "Jeff Smith",
      "Lynda Barry",
      "Marjane Satrapi",
      "Alison Bechdel",
      "Tove Jansson",
      "Posy Simmonds",
      "Adrian Tomine",
      "Daniel Clowes",
      "Jaime Hernandez",
      "Gilbert Hernandez",
      "Sergio Aragones"
    ]), priority: 1 },
    { ...makeCategory("actor-names", "actor names", [
      "Tom Hanks",
      "Meryl Streep",
      "Denzel Washington",
      "Cate Blanchett",
      "Leonardo DiCaprio",
      "Viola Davis",
      "Brad Pitt",
      "Nicole Kidman",
      "Robert De Niro",
      "Emma Stone",
      "Ryan Gosling",
      "Julia Roberts",
      "Samuel L. Jackson",
      "Sandra Bullock",
      "Christian Bale",
      "Charlize Theron",
      "Matt Damon",
      "Jodie Foster",
      "Idris Elba",
      "Amy Adams",
      "Harrison Ford",
      "Scarlett Johansson",
      "Jake Gyllenhaal",
      "Saoirse Ronan",
      "Mahershala Ali",
      "Frances McDormand",
      "Cillian Murphy",
      "Florence Pugh",
      "Angela Bassett",
      "Benedict Cumberbatch",
      "Rachel Weisz",
      "Colin Farrell",
      "Margot Robbie",
      "Willem Dafoe",
      "Michelle Yeoh",
      "Keanu Reeves",
      "Jeff Bridges",
      "Naomi Watts",
      "Paul Mescal",
      "Pedro Pascal",
      "Zendaya",
      "Andrew Garfield",
      "Regina King",
      "Carey Mulligan",
      "Ayo Edebiri"
    ]), priority: 1 },
    { ...makeCategory("movie-titles", "movie titles", [
      "The Matrix",
      "Inception",
      "Titanic",
      "Avatar",
      "Gladiator",
      "Interstellar",
      "The Godfather",
      "Pulp Fiction",
      "The Dark Knight",
      "Forrest Gump",
      "Casablanca",
      "Jaws",
      "Alien",
      "Rocky",
      "Goodfellas",
      "The Departed",
      "Whiplash",
      "Arrival",
      "Barbie",
      "Oppenheimer",
      "La La Land",
      "Moonlight",
      "Parasite",
      "The Shawshank Redemption",
      "The Silence of the Lambs",
      "Jurassic Park",
      "Back to the Future",
      "The Truman Show",
      "No Country for Old Men",
      "There Will Be Blood",
      "Blade Runner",
      "Top Gun",
      "Toy Story",
      "Finding Nemo",
      "The Lion King",
      "Die Hard",
      "Get Out",
      "Her",
      "The Social Network",
      "Little Women",
      "A Few Good Men",
      "The Prestige",
      "Shrek",
      "Memento",
      "The Grand Budapest Hotel"
    ]), priority: 1 },
    { ...makeCategory("song-titles", "song titles", [
      "Imagine",
      "Halo",
      "Firework",
      "Bad Guy",
      "Stay",
      "Uptown Funk",
      "Royals",
      "Poker Face",
      "Yellow",
      "Wonderwall",
      "Hey Jude",
      "Purple Rain",
      "Rolling in the Deep",
      "Single Ladies",
      "Shake It Off",
      "Levitating",
      "Viva La Vida",
      "Mr. Brightside",
      "Call Me Maybe",
      "Watermelon Sugar",
      "Take on Me",
      "Dancing Queen",
      "Bohemian Rhapsody",
      "Toxic",
      "Since U Been Gone",
      "Teenage Dream",
      "Blinding Lights",
      "Umbrella",
      "Hello",
      "Dreams",
      "Africa",
      "Creep",
      "Landslide",
      "Jolene",
      "Fast Car",
      "I Will Survive",
      "Respect",
      "Crazy in Love",
      "Hound Dog",
      "Billie Jean",
      "Like a Prayer",
      "Material Girl",
      "As It Was",
      "Flowers",
      "Shallow"
    ]), priority: 1 },
    { ...makeCategory("dog-breeds", "dog breeds", [
      "Labrador Retriever",
      "Golden Retriever",
      "German Shepherd",
      "French Bulldog",
      "Poodle",
      "Beagle",
      "Rottweiler",
      "Dachshund",
      "Siberian Husky",
      "Boxer",
      "Doberman Pinscher",
      "Great Dane",
      "Shih Tzu",
      "Chihuahua",
      "Border Collie",
      "Australian Shepherd",
      "Cocker Spaniel",
      "Boston Terrier",
      "Pug",
      "Mastiff",
      "Saint Bernard",
      "Bichon Frise",
      "Akita",
      "Samoyed",
      "Weimaraner",
      "Newfoundland",
      "Bernese Mountain Dog",
      "Belgian Malinois",
      "Greyhound",
      "Whippet",
      "Papillon",
      "Pomeranian",
      "Bull Terrier",
      "Cane Corso",
      "Shar Pei",
      "Alaskan Malamute",
      "Basenji",
      "Bloodhound",
      "Dalmatian",
      "English Bulldog",
      "Fox Terrier",
      "Irish Setter",
      "Jack Russell Terrier",
      "Vizsla",
      "Yorkshire Terrier"
    ]), priority: 1 },
  ];

  const preferred = [
    ...buildChunkedCategories("flowers", 2, "flower", 2),
    ...buildChunkedCategories("trees", 2, "tree", 2),
    ...buildChunkedCategories("birds", 2, "bird", 2),
    ...buildChunkedCategories("insects", 2, "insect", 2),
    ...buildChunkedCategories("gemstones", 2, "gemstone", 2),
    ...buildChunkedCategories("cheeses", 2, "cheese", 2),
    ...buildChunkedCategories("breads", 2, "bread", 2),
    ...buildChunkedCategories("desserts", 2, "dessert", 2),
    ...buildChunkedCategories("candies", 2, "candie", 2),
    ...buildChunkedCategories("cereals", 2, "cereal", 2),
    ...buildChunkedCategories("kitchen-tools", 2, "kitchen tool", 2),
    ...buildChunkedCategories("garden-tools", 2, "garden tool", 2),
    ...buildChunkedCategories("cleaning-supplies", 2, "cleaning supplie", 2),
    ...buildChunkedCategories("board-games", 2, "board game", 2),
    ...buildChunkedCategories("medical-dramas", 2, "medical drama", 2),
    ...buildChunkedCategories("sitcoms", 2, "sitcom", 2),
    ...buildChunkedCategories("authors", 2, "author", 2),
    ...buildChunkedCategories("directors", 2, "director", 2),
    ...buildChunkedCategories("painters", 2, "painter", 2),
    ...buildChunkedCategories("composers", 2, "composer", 2),
    ...buildChunkedCategories("poets", 2, "poet", 2),
    ...buildChunkedCategories("scientists", 2, "scientist", 2),
    ...buildChunkedCategories("philosophers", 2, "philosopher", 2),
    ...buildChunkedCategories("mythological-figures", 2, "mythological figure", 2),
    ...buildChunkedCategories("constellations", 2, "constellation", 2),
    ...buildChunkedCategories("capital-cities", 2, "capital citie", 2),
    ...buildChunkedCategories("kitchen-appliances", 2, "kitchen appliance", 2),
    ...buildChunkedCategories("furniture", 2, "furniture", 2),
    ...buildChunkedCategories("sea-creatures", 2, "sea creature", 2),
    ...buildChunkedCategories("dinosaurs", 2, "dinosaur", 2),
    ...buildChunkedCategories("car-brands", 2, "car brand", 2),
    ...buildChunkedCategories("fashion-brands", 2, "fashion brand", 2),
    ...buildChunkedCategories("luxury-brands", 2, "luxury brand", 2),
  ];

  const archive = [
    ...buildChunkedCategories("archive-theme-1", 2, "archive theme 1", 3),
    ...buildChunkedCategories("archive-theme-2", 2, "archive theme 2", 3),
    ...buildChunkedCategories("archive-theme-3", 2, "archive theme 3", 3),
    ...buildChunkedCategories("archive-theme-4", 2, "archive theme 4", 3),
    ...buildChunkedCategories("archive-theme-5", 2, "archive theme 5", 3),
    ...buildChunkedCategories("archive-theme-6", 2, "archive theme 6", 3),
    ...buildChunkedCategories("archive-theme-7", 2, "archive theme 7", 3),
    ...buildChunkedCategories("archive-theme-8", 2, "archive theme 8", 3),
    ...buildChunkedCategories("archive-theme-9", 2, "archive theme 9", 3),
    ...buildChunkedCategories("archive-theme-10", 2, "archive theme 10", 3),
    ...buildChunkedCategories("archive-theme-11", 2, "archive theme 11", 3),
    ...buildChunkedCategories("archive-theme-12", 2, "archive theme 12", 3),
    ...buildChunkedCategories("archive-theme-13", 2, "archive theme 13", 3),
    ...buildChunkedCategories("archive-theme-14", 2, "archive theme 14", 3),
    ...buildChunkedCategories("archive-theme-15", 2, "archive theme 15", 3),
    ...buildChunkedCategories("archive-theme-16", 2, "archive theme 16", 3),
    ...buildChunkedCategories("archive-theme-17", 2, "archive theme 17", 3),
    ...buildChunkedCategories("archive-theme-18", 2, "archive theme 18", 3),
    ...buildChunkedCategories("archive-theme-19", 2, "archive theme 19", 3),
    ...buildChunkedCategories("archive-theme-20", 2, "archive theme 20", 3),
    ...buildChunkedCategories("archive-theme-21", 2, "archive theme 21", 3),
    ...buildChunkedCategories("archive-theme-22", 2, "archive theme 22", 3),
    ...buildChunkedCategories("archive-theme-23", 2, "archive theme 23", 3),
    ...buildChunkedCategories("archive-theme-24", 2, "archive theme 24", 3),
    ...buildChunkedCategories("archive-theme-25", 2, "archive theme 25", 3),
    ...buildChunkedCategories("archive-theme-26", 2, "archive theme 26", 3),
    ...buildChunkedCategories("archive-theme-27", 2, "archive theme 27", 3),
    ...buildChunkedCategories("archive-theme-28", 2, "archive theme 28", 3),
    ...buildChunkedCategories("archive-theme-29", 2, "archive theme 29", 3),
    ...buildChunkedCategories("archive-theme-30", 2, "archive theme 30", 3),
    ...buildChunkedCategories("archive-theme-31", 2, "archive theme 31", 3),
    ...buildChunkedCategories("archive-theme-32", 2, "archive theme 32", 3),
    ...buildChunkedCategories("archive-theme-33", 2, "archive theme 33", 3),
    ...buildChunkedCategories("archive-theme-34", 2, "archive theme 34", 3),
    ...buildChunkedCategories("archive-theme-35", 2, "archive theme 35", 3),
    ...buildChunkedCategories("archive-theme-36", 2, "archive theme 36", 3),
    ...buildChunkedCategories("archive-theme-37", 2, "archive theme 37", 3),
    ...buildChunkedCategories("archive-theme-38", 2, "archive theme 38", 3),
    ...buildChunkedCategories("archive-theme-39", 2, "archive theme 39", 3),
    ...buildChunkedCategories("archive-theme-40", 2, "archive theme 40", 3),
    ...buildChunkedCategories("archive-theme-41", 2, "archive theme 41", 3),
    ...buildChunkedCategories("archive-theme-42", 2, "archive theme 42", 3),
    ...buildChunkedCategories("archive-theme-43", 2, "archive theme 43", 3),
    ...buildChunkedCategories("archive-theme-44", 2, "archive theme 44", 3),
    ...buildChunkedCategories("archive-theme-45", 2, "archive theme 45", 3),
    ...buildChunkedCategories("archive-theme-46", 2, "archive theme 46", 3),
    ...buildChunkedCategories("archive-theme-47", 2, "archive theme 47", 3),
    ...buildChunkedCategories("archive-theme-48", 2, "archive theme 48", 3),
    ...buildChunkedCategories("archive-theme-49", 2, "archive theme 49", 3),
    ...buildChunkedCategories("archive-theme-50", 2, "archive theme 50", 3),
    ...buildChunkedCategories("archive-theme-51", 2, "archive theme 51", 3),
    ...buildChunkedCategories("archive-theme-52", 2, "archive theme 52", 3),
    ...buildChunkedCategories("archive-theme-53", 2, "archive theme 53", 3),
    ...buildChunkedCategories("archive-theme-54", 2, "archive theme 54", 3),
    ...buildChunkedCategories("archive-theme-55", 2, "archive theme 55", 3),
    ...buildChunkedCategories("archive-theme-56", 2, "archive theme 56", 3),
    ...buildChunkedCategories("archive-theme-57", 2, "archive theme 57", 3),
    ...buildChunkedCategories("archive-theme-58", 2, "archive theme 58", 3),
    ...buildChunkedCategories("archive-theme-59", 2, "archive theme 59", 3),
    ...buildChunkedCategories("archive-theme-60", 2, "archive theme 60", 3),
    ...buildChunkedCategories("archive-theme-61", 2, "archive theme 61", 3),
    ...buildChunkedCategories("archive-theme-62", 2, "archive theme 62", 3),
    ...buildChunkedCategories("archive-theme-63", 2, "archive theme 63", 3),
    ...buildChunkedCategories("archive-theme-64", 2, "archive theme 64", 3),
    ...buildChunkedCategories("archive-theme-65", 2, "archive theme 65", 3),
    ...buildChunkedCategories("archive-theme-66", 2, "archive theme 66", 3),
    ...buildChunkedCategories("archive-theme-67", 2, "archive theme 67", 3),
    ...buildChunkedCategories("archive-theme-68", 2, "archive theme 68", 3),
    ...buildChunkedCategories("archive-theme-69", 2, "archive theme 69", 3),
    ...buildChunkedCategories("archive-theme-70", 2, "archive theme 70", 3),
    ...buildChunkedCategories("archive-theme-71", 2, "archive theme 71", 3),
    ...buildChunkedCategories("archive-theme-72", 2, "archive theme 72", 3),
    ...buildChunkedCategories("archive-theme-73", 2, "archive theme 73", 3),
    ...buildChunkedCategories("archive-theme-74", 2, "archive theme 74", 3),
    ...buildChunkedCategories("archive-theme-75", 2, "archive theme 75", 3),
    ...buildChunkedCategories("archive-theme-76", 2, "archive theme 76", 3),
    ...buildChunkedCategories("archive-theme-77", 2, "archive theme 77", 3),
    ...buildChunkedCategories("archive-theme-78", 2, "archive theme 78", 3),
    ...buildChunkedCategories("archive-theme-79", 2, "archive theme 79", 3),
    ...buildChunkedCategories("archive-theme-80", 2, "archive theme 80", 3),
    ...buildChunkedCategories("archive-theme-81", 2, "archive theme 81", 3),
    ...buildChunkedCategories("archive-theme-82", 2, "archive theme 82", 3),
    ...buildChunkedCategories("archive-theme-83", 2, "archive theme 83", 3),
    ...buildChunkedCategories("archive-theme-84", 2, "archive theme 84", 3),
    ...buildChunkedCategories("archive-theme-85", 2, "archive theme 85", 3),
    ...buildChunkedCategories("archive-theme-86", 2, "archive theme 86", 3),
    ...buildChunkedCategories("archive-theme-87", 2, "archive theme 87", 3),
    ...buildChunkedCategories("archive-theme-88", 2, "archive theme 88", 3),
    ...buildChunkedCategories("archive-theme-89", 2, "archive theme 89", 3),
    ...buildChunkedCategories("archive-theme-90", 2, "archive theme 90", 3),
    ...buildChunkedCategories("archive-theme-91", 2, "archive theme 91", 3),
    ...buildChunkedCategories("archive-theme-92", 2, "archive theme 92", 3),
    ...buildChunkedCategories("archive-theme-93", 2, "archive theme 93", 3),
    ...buildChunkedCategories("archive-theme-94", 2, "archive theme 94", 3),
    ...buildChunkedCategories("archive-theme-95", 2, "archive theme 95", 3),
    ...buildChunkedCategories("archive-theme-96", 2, "archive theme 96", 3),
    ...buildChunkedCategories("archive-theme-97", 2, "archive theme 97", 3),
    ...buildChunkedCategories("archive-theme-98", 2, "archive theme 98", 3),
    ...buildChunkedCategories("archive-theme-99", 2, "archive theme 99", 3),
    ...buildChunkedCategories("archive-theme-100", 2, "archive theme 100", 3),
    ...buildChunkedCategories("archive-theme-101", 2, "archive theme 101", 3),
    ...buildChunkedCategories("archive-theme-102", 2, "archive theme 102", 3),
    ...buildChunkedCategories("archive-theme-103", 2, "archive theme 103", 3),
    ...buildChunkedCategories("archive-theme-104", 2, "archive theme 104", 3),
    ...buildChunkedCategories("archive-theme-105", 2, "archive theme 105", 3),
    ...buildChunkedCategories("archive-theme-106", 2, "archive theme 106", 3),
    ...buildChunkedCategories("archive-theme-107", 2, "archive theme 107", 3),
    ...buildChunkedCategories("archive-theme-108", 2, "archive theme 108", 3),
    ...buildChunkedCategories("archive-theme-109", 2, "archive theme 109", 3),
    ...buildChunkedCategories("archive-theme-110", 2, "archive theme 110", 3),
    ...buildChunkedCategories("archive-theme-111", 2, "archive theme 111", 3),
    ...buildChunkedCategories("archive-theme-112", 2, "archive theme 112", 3),
    ...buildChunkedCategories("archive-theme-113", 2, "archive theme 113", 3),
    ...buildChunkedCategories("archive-theme-114", 2, "archive theme 114", 3),
    ...buildChunkedCategories("archive-theme-115", 2, "archive theme 115", 3),
    ...buildChunkedCategories("archive-theme-116", 2, "archive theme 116", 3),
    ...buildChunkedCategories("archive-theme-117", 2, "archive theme 117", 3),
    ...buildChunkedCategories("archive-theme-118", 2, "archive theme 118", 3),
    ...buildChunkedCategories("archive-theme-119", 2, "archive theme 119", 3),
    ...buildChunkedCategories("archive-theme-120", 2, "archive theme 120", 3),
    ...buildChunkedCategories("archive-theme-121", 2, "archive theme 121", 3),
    ...buildChunkedCategories("archive-theme-122", 2, "archive theme 122", 3),
    ...buildChunkedCategories("archive-theme-123", 2, "archive theme 123", 3),
    ...buildChunkedCategories("archive-theme-124", 2, "archive theme 124", 3),
    ...buildChunkedCategories("archive-theme-125", 2, "archive theme 125", 3),
    ...buildChunkedCategories("archive-theme-126", 2, "archive theme 126", 3),
    ...buildChunkedCategories("archive-theme-127", 2, "archive theme 127", 3),
    ...buildChunkedCategories("archive-theme-128", 2, "archive theme 128", 3),
    ...buildChunkedCategories("archive-theme-129", 2, "archive theme 129", 3),
    ...buildChunkedCategories("archive-theme-130", 2, "archive theme 130", 3),
    ...buildChunkedCategories("archive-theme-131", 2, "archive theme 131", 3),
    ...buildChunkedCategories("archive-theme-132", 2, "archive theme 132", 3),
    ...buildChunkedCategories("archive-theme-133", 2, "archive theme 133", 3),
    ...buildChunkedCategories("archive-theme-134", 2, "archive theme 134", 3),
    ...buildChunkedCategories("archive-theme-135", 2, "archive theme 135", 3),
    ...buildChunkedCategories("archive-theme-136", 2, "archive theme 136", 3),
    ...buildChunkedCategories("archive-theme-137", 2, "archive theme 137", 3),
    ...buildChunkedCategories("archive-theme-138", 2, "archive theme 138", 3),
    ...buildChunkedCategories("archive-theme-139", 2, "archive theme 139", 3),
    ...buildChunkedCategories("archive-theme-140", 2, "archive theme 140", 3),
    ...buildChunkedCategories("archive-theme-141", 2, "archive theme 141", 3),
    ...buildChunkedCategories("archive-theme-142", 2, "archive theme 142", 3),
    ...buildChunkedCategories("archive-theme-143", 2, "archive theme 143", 3),
    ...buildChunkedCategories("archive-theme-144", 2, "archive theme 144", 3),
    ...buildChunkedCategories("archive-theme-145", 2, "archive theme 145", 3),
    ...buildChunkedCategories("archive-theme-146", 2, "archive theme 146", 3),
    ...buildChunkedCategories("archive-theme-147", 2, "archive theme 147", 3),
    ...buildChunkedCategories("archive-theme-148", 2, "archive theme 148", 3),
    ...buildChunkedCategories("archive-theme-149", 2, "archive theme 149", 3),
    ...buildChunkedCategories("archive-theme-150", 2, "archive theme 150", 3),
    ...buildChunkedCategories("archive-theme-151", 2, "archive theme 151", 3),
    ...buildChunkedCategories("archive-theme-152", 2, "archive theme 152", 3),
    ...buildChunkedCategories("archive-theme-153", 2, "archive theme 153", 3),
    ...buildChunkedCategories("archive-theme-154", 2, "archive theme 154", 3),
    ...buildChunkedCategories("archive-theme-155", 2, "archive theme 155", 3),
    ...buildChunkedCategories("archive-theme-156", 2, "archive theme 156", 3),
    ...buildChunkedCategories("archive-theme-157", 2, "archive theme 157", 3),
    ...buildChunkedCategories("archive-theme-158", 2, "archive theme 158", 3),
    ...buildChunkedCategories("archive-theme-159", 2, "archive theme 159", 3),
    ...buildChunkedCategories("archive-theme-160", 2, "archive theme 160", 3),
    ...buildChunkedCategories("archive-theme-161", 2, "archive theme 161", 3),
    ...buildChunkedCategories("archive-theme-162", 2, "archive theme 162", 3),
    ...buildChunkedCategories("archive-theme-163", 2, "archive theme 163", 3),
    ...buildChunkedCategories("archive-theme-164", 2, "archive theme 164", 3),
    ...buildChunkedCategories("archive-theme-165", 2, "archive theme 165", 3),
    ...buildChunkedCategories("archive-theme-166", 2, "archive theme 166", 3),
    ...buildChunkedCategories("archive-theme-167", 2, "archive theme 167", 3),
    ...buildChunkedCategories("archive-theme-168", 2, "archive theme 168", 3),
    ...buildChunkedCategories("archive-theme-169", 2, "archive theme 169", 3),
    ...buildChunkedCategories("archive-theme-170", 2, "archive theme 170", 3),
    ...buildChunkedCategories("archive-theme-171", 2, "archive theme 171", 3),
    ...buildChunkedCategories("archive-theme-172", 2, "archive theme 172", 3),
    ...buildChunkedCategories("archive-theme-173", 2, "archive theme 173", 3),
    ...buildChunkedCategories("archive-theme-174", 2, "archive theme 174", 3),
    ...buildChunkedCategories("archive-theme-175", 2, "archive theme 175", 3),
    ...buildChunkedCategories("archive-theme-176", 2, "archive theme 176", 3),
    ...buildChunkedCategories("archive-theme-177", 2, "archive theme 177", 3),
    ...buildChunkedCategories("archive-theme-178", 2, "archive theme 178", 3),
    ...buildChunkedCategories("archive-theme-179", 2, "archive theme 179", 3),
    ...buildChunkedCategories("archive-theme-180", 2, "archive theme 180", 3),
    ...buildChunkedCategories("archive-theme-181", 2, "archive theme 181", 3),
    ...buildChunkedCategories("archive-theme-182", 2, "archive theme 182", 3),
    ...buildChunkedCategories("archive-theme-183", 2, "archive theme 183", 3),
    ...buildChunkedCategories("archive-theme-184", 2, "archive theme 184", 3),
    ...buildChunkedCategories("archive-theme-185", 2, "archive theme 185", 3),
    ...buildChunkedCategories("archive-theme-186", 2, "archive theme 186", 3),
    ...buildChunkedCategories("archive-theme-187", 2, "archive theme 187", 3),
    ...buildChunkedCategories("archive-theme-188", 2, "archive theme 188", 3),
    ...buildChunkedCategories("archive-theme-189", 2, "archive theme 189", 3),
    ...buildChunkedCategories("archive-theme-190", 2, "archive theme 190", 3),
    ...buildChunkedCategories("archive-theme-191", 2, "archive theme 191", 3),
    ...buildChunkedCategories("archive-theme-192", 2, "archive theme 192", 3),
    ...buildChunkedCategories("archive-theme-193", 2, "archive theme 193", 3),
    ...buildChunkedCategories("archive-theme-194", 2, "archive theme 194", 3),
    ...buildChunkedCategories("archive-theme-195", 2, "archive theme 195", 3),
    ...buildChunkedCategories("archive-theme-196", 2, "archive theme 196", 3),
    ...buildChunkedCategories("archive-theme-197", 2, "archive theme 197", 3),
    ...buildChunkedCategories("archive-theme-198", 2, "archive theme 198", 3),
    ...buildChunkedCategories("archive-theme-199", 2, "archive theme 199", 3),
    ...buildChunkedCategories("archive-theme-200", 2, "archive theme 200", 3),
    ...buildChunkedCategories("archive-theme-201", 2, "archive theme 201", 3),
    ...buildChunkedCategories("archive-theme-202", 2, "archive theme 202", 3),
    ...buildChunkedCategories("archive-theme-203", 2, "archive theme 203", 3),
    ...buildChunkedCategories("archive-theme-204", 2, "archive theme 204", 3),
    ...buildChunkedCategories("archive-theme-205", 2, "archive theme 205", 3),
    ...buildChunkedCategories("archive-theme-206", 2, "archive theme 206", 3),
    ...buildChunkedCategories("archive-theme-207", 2, "archive theme 207", 3),
    ...buildChunkedCategories("archive-theme-208", 2, "archive theme 208", 3),
    ...buildChunkedCategories("archive-theme-209", 2, "archive theme 209", 3),
    ...buildChunkedCategories("archive-theme-210", 2, "archive theme 210", 3),
    ...buildChunkedCategories("archive-theme-211", 2, "archive theme 211", 3),
    ...buildChunkedCategories("archive-theme-212", 2, "archive theme 212", 3),
    ...buildChunkedCategories("archive-theme-213", 2, "archive theme 213", 3),
    ...buildChunkedCategories("archive-theme-214", 2, "archive theme 214", 3),
    ...buildChunkedCategories("archive-theme-215", 2, "archive theme 215", 3),
    ...buildChunkedCategories("archive-theme-216", 2, "archive theme 216", 3),
    ...buildChunkedCategories("archive-theme-217", 2, "archive theme 217", 3),
    ...buildChunkedCategories("archive-theme-218", 2, "archive theme 218", 3),
    ...buildChunkedCategories("archive-theme-219", 2, "archive theme 219", 3),
    ...buildChunkedCategories("archive-theme-220", 2, "archive theme 220", 3),
    ...buildChunkedCategories("archive-theme-221", 2, "archive theme 221", 3),
    ...buildChunkedCategories("archive-theme-222", 2, "archive theme 222", 3),
    ...buildChunkedCategories("archive-theme-223", 2, "archive theme 223", 3),
    ...buildChunkedCategories("archive-theme-224", 2, "archive theme 224", 3),
    ...buildChunkedCategories("archive-theme-225", 2, "archive theme 225", 3),
    ...buildChunkedCategories("archive-theme-226", 2, "archive theme 226", 3),
    ...buildChunkedCategories("archive-theme-227", 2, "archive theme 227", 3),
  ];

  const bank = [...explicit, ...preferred, ...archive];
  if (bank.length < 500) throw new Error(`Category bank too small: ${bank.length}`);
  return bank;
}

window.buildCategoryBank = buildCategoryBank;
