window.CATEGORY_BANK = [
  {
    "id": "pasta-types",
    "title": "pasta types",
    "items": [
      "spaghetti",
      "penne",
      "rigatoni",
      "fusilli",
      "farfalle",
      "linguine",
      "fettuccine",
      "ravioli",
      "tortellini",
      "gnocchi",
      "ziti",
      "macaroni",
      "cavatappi",
      "rotini",
      "bucatini",
      "orecchiette",
      "pappardelle",
      "lasagna",
      "tagliatelle",
      "vermicelli",
      "angel hair",
      "ditalini",
      "manicotti",
      "capellini",
      "gemelli",
      "mafaldine",
      "radiatori",
      "campanelle",
      "strozzapreti",
      "paccheri",
      "anelletti",
      "bigoli",
      "casarecce",
      "trofie",
      "malloreddus",
      "lumache",
      "fregola",
      "mezzi rigatoni",
      "spaghettini",
      "cellentani",
      "tubetti",
      "sedani",
      "filini",
      "orzo",
      "cannelloni"
    ]
  },
  {
    "id": "coffee-drinks",
    "title": "coffee drinks",
    "items": [
      "espresso",
      "americano",
      "latte",
      "cappuccino",
      "flat white",
      "macchiato",
      "mocha",
      "cortado",
      "ristretto",
      "lungo",
      "affogato",
      "red eye",
      "black eye",
      "drip coffee",
      "pour-over",
      "cold brew",
      "nitro cold brew",
      "iced coffee",
      "frappe",
      "freddo espresso",
      "freddo cappuccino",
      "irish coffee",
      "turkish coffee",
      "cafe au lait",
      "cafe bombon",
      "cafe crema",
      "cafe cubano",
      "doppio",
      "piccolo latte",
      "dirty chai",
      "mazagran",
      "vienna coffee",
      "breve",
      "bulletproof coffee",
      "instant coffee",
      "decaf coffee",
      "filter coffee",
      "aeropress coffee",
      "chemex coffee",
      "espresso con panna",
      "iced latte",
      "iced americano",
      "iced mocha",
      "shakerato",
      "kopi tubruk"
    ]
  },
  {
    "id": "spices-herbs",
    "title": "spices & herbs",
    "items": [
      "basil",
      "oregano",
      "thyme",
      "rosemary",
      "cumin",
      "turmeric",
      "paprika",
      "cinnamon",
      "nutmeg",
      "clove",
      "cardamom",
      "parsley",
      "dill",
      "sage",
      "tarragon",
      "sumac",
      "za'atar",
      "bay leaf",
      "fennel",
      "anise",
      "chives",
      "mint",
      "marjoram",
      "caraway",
      "coriander",
      "ginger",
      "allspice",
      "saffron",
      "vanilla",
      "sesame",
      "mustard seed",
      "celery seed",
      "fenugreek",
      "star anise",
      "lemongrass",
      "chili powder",
      "cayenne",
      "garlic powder",
      "onion powder",
      "smoked paprika",
      "herbes de Provence",
      "lovage",
      "savory",
      "asafoetida",
      "nigella"
    ]
  },
  {
    "id": "trees",
    "title": "trees",
    "items": [
      "oak",
      "maple",
      "pine",
      "spruce",
      "fir",
      "cedar",
      "birch",
      "elm",
      "ash",
      "willow",
      "poplar",
      "beech",
      "sycamore",
      "hemlock",
      "yew",
      "redwood",
      "sequoia",
      "larch",
      "alder",
      "cherry",
      "apple",
      "pear",
      "plum",
      "hawthorn",
      "holly",
      "juniper",
      "magnolia",
      "dogwood",
      "walnut",
      "chestnut",
      "hickory",
      "cypress",
      "eucalyptus",
      "baobab",
      "olive",
      "fig",
      "mulberry",
      "cottonwood",
      "rowan",
      "ginkgo",
      "acacia",
      "aspen",
      "hornbeam",
      "lime",
      "teak"
    ]
  },
  {
    "id": "flowers",
    "title": "flowers",
    "items": [
      "rose",
      "tulip",
      "daisy",
      "lily",
      "orchid",
      "peony",
      "sunflower",
      "lavender",
      "iris",
      "marigold",
      "daffodil",
      "hyacinth",
      "poppy",
      "camellia",
      "gardenia",
      "begonia",
      "zinnia",
      "petunia",
      "snapdragon",
      "aster",
      "hydrangea",
      "chrysanthemum",
      "violet",
      "lotus",
      "anemone",
      "delphinium",
      "foxglove",
      "freesia",
      "gladiolus",
      "hibiscus",
      "hollyhock",
      "jasmine",
      "lilac",
      "nasturtium",
      "phlox",
      "ranunculus",
      "sweet pea",
      "verbena",
      "wisteria",
      "yarrow",
      "cosmos",
      "dahlia",
      "geranium",
      "bluebell",
      "azalea"
    ]
  },
  {
    "id": "colours",
    "title": "colours",
    "items": [
      "red",
      "blue",
      "green",
      "yellow colour",
      "orange",
      "purple",
      "pink colour",
      "brown",
      "black",
      "white",
      "grey",
      "beige",
      "teal",
      "turquoise blue",
      "magenta",
      "maroon",
      "navy",
      "lavender purple",
      "violet purple",
      "indigo",
      "crimson",
      "scarlet",
      "amber yellow",
      "gold",
      "silver",
      "bronze",
      "ivory",
      "cream",
      "charcoal",
      "peach",
      "coral pink",
      "mint green",
      "olive green",
      "mustard",
      "burgundy",
      "plum purple",
      "lilac purple",
      "taupe",
      "ochre",
      "aqua",
      "cyan",
      "periwinkle",
      "fuchsia",
      "khaki",
      "cerulean"
    ]
  },
  {
    "id": "items-of-clothing",
    "title": "items of clothing",
    "items": [
      "t-shirt",
      "shirt",
      "blouse",
      "sweater",
      "hoodie",
      "cardigan",
      "jacket",
      "coat",
      "blazer",
      "dress",
      "skirt",
      "jeans",
      "trousers",
      "shorts",
      "leggings",
      "socks",
      "tights",
      "scarf",
      "hat",
      "cap",
      "beanie",
      "gloves",
      "mittens",
      "belt",
      "tie",
      "bow tie",
      "vest",
      "waistcoat",
      "raincoat",
      "parka",
      "polo shirt",
      "tank top",
      "camisole",
      "jumpsuit",
      "romper",
      "pyjamas",
      "nightgown",
      "bathrobe",
      "swimsuit",
      "bikini",
      "trench coat",
      "windbreaker",
      "poncho",
      "overalls",
      "suit"
    ]
  },
  {
    "id": "technology-items",
    "title": "technology items",
    "items": [
      "laptop",
      "desktop computer",
      "tablet",
      "smartphone",
      "smartwatch",
      "printer",
      "scanner",
      "router",
      "modem",
      "keyboard",
      "mouse",
      "monitor",
      "webcam",
      "microphone",
      "headphones",
      "earbuds",
      "speaker",
      "projector",
      "external hard drive",
      "usb flash drive",
      "graphics card",
      "motherboard",
      "processor",
      "ram stick",
      "power bank",
      "charging cable",
      "wireless charger",
      "game console",
      "vr headset",
      "drone",
      "digital camera",
      "tripod",
      "smart bulb",
      "smart thermostat",
      "streaming stick",
      "e-reader",
      "calculator",
      "3D printer",
      "network switch",
      "surge protector",
      "ssd",
      "nas drive",
      "drawing tablet",
      "blu-ray player",
      "alarm clock"
    ]
  },
  {
    "id": "tech-companies",
    "title": "tech companies",
    "items": [
      "Apple Inc.",
      "Microsoft",
      "Google",
      "Amazon",
      "Meta",
      "Netflix",
      "Spotify",
      "Adobe",
      "Intel",
      "AMD",
      "Nvidia",
      "Samsung",
      "Sony",
      "LG",
      "Dell",
      "HP",
      "Lenovo",
      "Asus",
      "Acer",
      "Cisco",
      "Oracle",
      "Salesforce",
      "Shopify",
      "Uber",
      "Airbnb",
      "PayPal",
      "eBay",
      "Snap",
      "Pinterest",
      "Zoom",
      "Dropbox",
      "Slack",
      "Reddit",
      "TikTok",
      "ByteDance",
      "Tencent",
      "Alibaba",
      "Huawei",
      "Xiaomi",
      "Qualcomm",
      "OpenAI",
      "Arm",
      "TSMC",
      "IBM",
      "Palantir"
    ]
  },
  {
    "id": "clothing-brands",
    "title": "clothing brands",
    "items": [
      "Nike",
      "Adidas",
      "Puma",
      "Reebok",
      "Under Armour",
      "Levi's",
      "Gap",
      "Old Navy",
      "Banana Republic",
      "Zara",
      "H&M",
      "Uniqlo",
      "Mango",
      "Abercrombie & Fitch",
      "Hollister",
      "Lululemon",
      "Aritzia",
      "American Eagle",
      "Madewell",
      "J.Crew",
      "Ralph Lauren",
      "Tommy Hilfiger",
      "Calvin Klein",
      "Patagonia",
      "The North Face",
      "Columbia",
      "Moncler",
      "Canada Goose",
      "Burberry",
      "Gucci",
      "Prada",
      "Versace",
      "Dior",
      "Chanel",
      "Hermes",
      "Louis Vuitton",
      "Coach",
      "Kate Spade",
      "Michael Kors",
      "Guess",
      "Diesel",
      "Superdry",
      "Everlane",
      "Fabletics",
      "Anthropologie"
    ]
  },
  {
    "id": "band-names",
    "title": "band names",
    "items": [
      "The Beatles",
      "The Rolling Stones",
      "Pink Floyd",
      "Led Zeppelin",
      "Queen",
      "The Who",
      "The Kinks",
      "The Beach Boys",
      "The Doors",
      "Fleetwood Mac",
      "ABBA",
      "U2",
      "R.E.M.",
      "Coldplay",
      "Radiohead",
      "Blur",
      "Oasis",
      "Nirvana",
      "Pearl Jam",
      "Green Day",
      "Foo Fighters",
      "Red Hot Chili Peppers",
      "The Killers",
      "Arctic Monkeys",
      "Imagine Dragons",
      "Maroon 5",
      "Linkin Park",
      "Fall Out Boy",
      "Paramore",
      "Mumford & Sons",
      "The Strokes",
      "Kings of Leon",
      "The Cure",
      "Depeche Mode",
      "The Smiths",
      "Journey",
      "Bon Jovi",
      "Aerosmith",
      "Metallica",
      "Iron Maiden",
      "Black Sabbath",
      "Kiss",
      "Heart",
      "The Cranberries",
      "Simple Minds"
    ]
  },
  {
    "id": "canadian-politicians",
    "title": "canadian politicians",
    "items": [
      "Justin Trudeau",
      "Pierre Trudeau",
      "Jagmeet Singh",
      "Pierre Poilievre",
      "Rachel Notley",
      "Danielle Smith",
      "Doug Ford",
      "Kathleen Wynne",
      "Andrea Horwath",
      "Olivia Chow",
      "Naheed Nenshi",
      "John Horgan",
      "David Eby",
      "Christy Clark",
      "Gordon Campbell",
      "Stephen Harper",
      "Preston Manning",
      "Jason Kenney",
      "Jean Chretien",
      "Paul Martin",
      "Michaelle Jean",
      "Adrienne Clarkson",
      "Belinda Stronach",
      "Rona Ambrose",
      "Lisa Raitt",
      "Dominic LeBlanc",
      "Chrystia Freeland",
      "Anita Anand",
      "Melanie Joly",
      "Francois Legault",
      "Yves-Francois Blanchet",
      "Gilles Duceppe",
      "Thomas Mulcair",
      "Jack Layton",
      "Elizabeth May",
      "Peter MacKay",
      "Erin O'Toole",
      "Patrick Brown",
      "Hazel McCallion",
      "David Miller",
      "Allan Rock",
      "John Turner",
      "Kim Campbell",
      "Brian Mulroney",
      "Marc Garneau"
    ]
  },
  {
    "id": "oscar-winning-actors",
    "title": "oscar-winning actors",
    "items": [
      "Tom Hanks",
      "Meryl Streep",
      "Denzel Washington",
      "Cate Blanchett",
      "Leonardo DiCaprio",
      "Viola Davis",
      "Emma Stone",
      "Daniel Day-Lewis",
      "Frances McDormand",
      "Mahershala Ali",
      "Jodie Foster",
      "Anthony Hopkins",
      "Charlize Theron",
      "Matthew McConaughey",
      "Nicole Kidman",
      "Sean Penn",
      "Julianne Moore",
      "Jamie Foxx",
      "Marion Cotillard",
      "Alicia Vikander",
      "Brie Larson",
      "Casey Affleck",
      "Gary Oldman",
      "Olivia Colman",
      "Joaquin Phoenix",
      "Renee Zellweger",
      "Youn Yuh-jung",
      "Jessica Chastain",
      "Brendan Fraser",
      "Cillian Murphy",
      "Michelle Yeoh",
      "Adrien Brody",
      "Natalie Portman",
      "Hilary Swank",
      "Russell Crowe",
      "Helen Mirren",
      "Jeff Bridges",
      "Jennifer Lawrence",
      "Forest Whitaker",
      "Penelope Cruz",
      "Laura Dern",
      "Rami Malek",
      "Reese Witherspoon",
      "Cuba Gooding Jr.",
      "Ariana DeBose"
    ]
  },
  {
    "id": "pop-stars",
    "title": "pop stars",
    "items": [
      "Madonna",
      "Britney Spears",
      "Taylor Swift",
      "Katy Perry",
      "Lady Gaga",
      "Dua Lipa",
      "Ariana Grande",
      "Olivia Rodrigo",
      "Billie Eilish",
      "Justin Bieber",
      "Shawn Mendes",
      "Harry Styles",
      "Miley Cyrus",
      "Selena Gomez",
      "Ed Sheeran",
      "Rihanna",
      "Kesha",
      "Lorde",
      "Sabrina Carpenter",
      "Troye Sivan",
      "Charli XCX",
      "Camila Cabello",
      "Demi Lovato",
      "Carly Rae Jepsen",
      "P!nk",
      "Christina Aguilera",
      "Backstreet Boys",
      "NSYNC",
      "One Direction",
      "Jonas Brothers",
      "Tate McRae",
      "Ava Max",
      "Zayn",
      "Lana Del Rey",
      "Halsey",
      "Bebe Rexha",
      "Meghan Trainor",
      "Niall Horan",
      "Kelly Clarkson",
      "Adam Lambert",
      "Conan Gray",
      "Tinashe",
      "Alessia Cara",
      "Gracie Abrams",
      "Dove Cameron"
    ]
  },
  {
    "id": "r-b-singers",
    "title": "r&b singers",
    "items": [
      "Usher",
      "Alicia Keys",
      "Mary J. Blige",
      "John Legend",
      "SZA",
      "Brandy",
      "Monica",
      "Toni Braxton",
      "Ciara",
      "Ne-Yo",
      "Miguel",
      "Jhene Aiko",
      "Summer Walker",
      "H.E.R.",
      "Khalid",
      "Bryson Tiller",
      "Tyrese",
      "Ginuwine",
      "Babyface",
      "Aaliyah",
      "Ashanti",
      "Tamia",
      "Faith Evans",
      "Musiq Soulchild",
      "Mario",
      "Omarion",
      "Trey Songz",
      "Keri Hilson",
      "Kehlani",
      "Daniel Caesar",
      "Giveon",
      "Muni Long",
      "Ella Mai",
      "Sade",
      "Lauryn Hill",
      "Janet Jackson",
      "Luther Vandross",
      "T-Pain",
      "112",
      "Joe",
      "Kelly Rowland",
      "Mya",
      "Maxwell",
      "Fantasia",
      "Robin Thicke"
    ]
  },
  {
    "id": "grey-s-anatomy-characters",
    "title": "grey's anatomy characters",
    "items": [
      "Meredith Grey",
      "Derek Shepherd",
      "Cristina Yang",
      "Alex Karev",
      "Miranda Bailey",
      "Richard Webber",
      "Izzie Stevens",
      "George O'Malley",
      "Callie Torres",
      "Arizona Robbins",
      "Mark Sloan",
      "Lexie Grey",
      "Jackson Avery",
      "April Kepner",
      "Owen Hunt",
      "Amelia Shepherd",
      "Maggie Pierce",
      "Jo Wilson",
      "Ben Warren",
      "Teddy Altman",
      "Addison Montgomery",
      "Preston Burke",
      "Atticus Lincoln",
      "Andrew DeLuca",
      "Tom Koracick",
      "Stephanie Edwards",
      "Levi Schmitt",
      "Helm",
      "Winston Ndugu",
      "Nick Marsh",
      "Carina DeLuca",
      "Catherine Fox",
      "Ellis Grey",
      "Adele Webber",
      "Denny Duquette",
      "Erica Hahn",
      "Finn Dandridge",
      "Penny Blake",
      "Megan Hunt",
      "Nathan Riggs",
      "Shane Ross",
      "Lucy Fields",
      "George O'Malley Sr.",
      "Nico Kim",
      "Schmitt"
    ]
  },
  {
    "id": "authors",
    "title": "authors",
    "items": [
      "Jane Austen",
      "Charles Dickens",
      "George Eliot",
      "Virginia Woolf",
      "James Joyce",
      "Toni Morrison",
      "Margaret Atwood",
      "Kazuo Ishiguro",
      "Salman Rushdie",
      "Donna Tartt",
      "C.S. Lewis",
      "J.R.R. Tolkien",
      "Harper Lee",
      "George Orwell",
      "Aldous Huxley",
      "F. Scott Fitzgerald",
      "Ernest Hemingway",
      "William Faulkner",
      "Emily Bronte",
      "Charlotte Bronte",
      "Anne Tyler",
      "Alice Munro",
      "Hilary Mantel",
      "Arundhati Roy",
      "Zadie Smith",
      "Ian McEwan",
      "Colson Whitehead",
      "Rachel Cusk",
      "Michael Ondaatje",
      "Maya Angelou",
      "Jhumpa Lahiri",
      "John Steinbeck",
      "Philip Roth",
      "Vladimir Nabokov",
      "Kurt Vonnegut",
      "Elena Ferrante",
      "John Irving",
      "Rohinton Mistry",
      "Margaret Laurence",
      "Mordecai Richler",
      "Alice Walker",
      "Louise Erdrich",
      "Ann Patchett",
      "David Mitchell",
      "Chimamanda Ngozi Adichie"
    ]
  },
  {
    "id": "painters",
    "title": "painters",
    "items": [
      "Pablo Picasso",
      "Vincent van Gogh",
      "Claude Monet",
      "Rembrandt",
      "Johannes Vermeer",
      "Edgar Degas",
      "Paul Cezanne",
      "Henri Matisse",
      "Wassily Kandinsky",
      "Jackson Pollock",
      "Georgia O'Keeffe",
      "Frida Kahlo",
      "Salvador Dali",
      "Edvard Munch",
      "Pierre-Auguste Renoir",
      "Paul Klee",
      "Joan Miro",
      "Gustav Klimt",
      "Jan van Eyck",
      "Sandro Botticelli",
      "Michelangelo",
      "Raphael",
      "Titian",
      "El Greco",
      "Caravaggio",
      "Diego Velazquez",
      "Francisco Goya",
      "J.M.W. Turner",
      "John Constable",
      "Caspar David Friedrich",
      "Mary Cassatt",
      "Berthe Morisot",
      "Camille Pissarro",
      "Georges Seurat",
      "Amedeo Modigliani",
      "Marc Chagall",
      "Henri Rousseau",
      "Egon Schiele",
      "Piet Mondrian",
      "Willem de Kooning",
      "Edward Hopper",
      "Grant Wood",
      "Winslow Homer",
      "Thomas Eakins",
      "Lucian Freud"
    ]
  },
  {
    "id": "directors",
    "title": "directors",
    "items": [
      "Steven Spielberg",
      "Martin Scorsese",
      "Christopher Nolan",
      "Greta Gerwig",
      "Spike Lee",
      "Sofia Coppola",
      "Ridley Scott",
      "James Cameron",
      "Kathryn Bigelow",
      "Guillermo del Toro",
      "Wes Anderson",
      "David Fincher",
      "Quentin Tarantino",
      "Patty Jenkins",
      "Bong Joon Ho",
      "Denis Villeneuve",
      "Jordan Peele",
      "Chloe Zhao",
      "Ava DuVernay",
      "Alfred Hitchcock",
      "Francis Ford Coppola",
      "Peter Jackson",
      "Tim Burton",
      "Stanley Kubrick",
      "Akira Kurosawa",
      "Hayao Miyazaki",
      "Ang Lee",
      "Jane Campion",
      "Jonathan Demme",
      "David Lynch",
      "Roman Polanski",
      "Sam Mendes",
      "Joel Coen",
      "Ethan Coen",
      "Barry Jenkins",
      "Todd Haynes",
      "Mike Leigh",
      "Ken Loach",
      "Clint Eastwood",
      "John Ford",
      "Orson Welles",
      "Paul Thomas Anderson",
      "Robert Altman",
      "Howard Hawks",
      "John Carpenter"
    ]
  },
  {
    "id": "comic-artists",
    "title": "comic artists",
    "items": [
      "Jack Kirby",
      "Stan Lee",
      "Steve Ditko",
      "Jim Lee",
      "Frank Miller",
      "Alan Moore",
      "Neal Adams",
      "Todd McFarlane",
      "John Romita Sr.",
      "John Byrne",
      "Alex Ross",
      "George Perez",
      "Brian Bolland",
      "Rob Liefeld",
      "Dave Gibbons",
      "Joe Kubert",
      "Will Eisner",
      "Art Spiegelman",
      "Chris Claremont",
      "Walt Simonson",
      "Carmine Infantino",
      "Gil Kane",
      "Mike Mignola",
      "Moebius",
      "Osamu Tezuka",
      "Rumiko Takahashi",
      "Katsuhiro Otomo",
      "Harvey Kurtzman",
      "Charles Schulz",
      "Bill Watterson",
      "Jim Davis",
      "Al Capp",
      "Herge",
      "R. Crumb",
      "Jeff Smith",
      "Lynda Barry",
      "Marjane Satrapi",
      "Alison Bechdel",
      "Tove Jansson",
      "Posy Simmonds",
      "Adrian Tomine",
      "Daniel Clowes",
      "Jaime Hernandez",
      "Gilbert Hernandez",
      "Sergio Aragones"
    ]
  },
  {
    "id": "animators",
    "title": "animators",
    "items": [
      "Glen Murakami",
      "Don Hertzfeldt",
      "Isao Takahata",
      "Glen Keane",
      "Andreas Deja",
      "Genndy Tartakovsky",
      "Don Bluth",
      "Chuck Jones",
      "Tex Avery",
      "Brad Bird",
      "John Lasseter",
      "Pete Docter",
      "Jennifer Lee",
      "Chris Sanders",
      "Dean DeBlois",
      "Rebecca Sugar",
      "Craig McCracken",
      "Pendleton Ward",
      "Matt Groening",
      "Seth MacFarlane",
      "Butch Hartman",
      "Jorge Gutierrez",
      "Nick Park",
      "Henry Selick",
      "Nina Paley",
      "Bill Plympton",
      "Richard Williams",
      "Friz Freleng",
      "Ub Iwerks",
      "John Kricfalusi",
      "Mike Judge",
      "Lauren Faust",
      "Joaquin Baldwin",
      "Michel Ocelot",
      "Satoshi Kon",
      "Makoto Shinkai",
      "Mamoru Hosoda",
      "Tadahito Mochinaga",
      "Bruno Bozzetto",
      "Bruce Timm",
      "Joanna Quinn",
      "Sylvain Chomet",
      "Tomm Moore",
      "Nora Twomey",
      "Shannon Tindle"
    ]
  },
  {
    "id": "greek-myth-figures",
    "title": "greek myth figures",
    "items": [
      "Zeus",
      "Hera",
      "Poseidon",
      "Demeter",
      "Athena",
      "Apollo",
      "Artemis",
      "Ares",
      "Aphrodite",
      "Aeolus",
      "Hephaestus",
      "Dionysus",
      "Hades",
      "Persephone",
      "Hestia",
      "Eros",
      "Eris",
      "Nemesis",
      "Hypnos",
      "Thanatos",
      "Hecate",
      "Pan",
      "Selene",
      "Helios",
      "Gaia",
      "Uranus",
      "Cronus",
      "Rhea",
      "Atlas",
      "Prometheus",
      "Epimetheus",
      "Perseus",
      "Heracles",
      "Theseus",
      "Jason",
      "Medea",
      "Orpheus",
      "Eurydice",
      "Achilles",
      "Patroclus",
      "Odysseus",
      "Penelope",
      "Circe",
      "Cassandra",
      "Andromeda"
    ]
  },
  {
    "id": "european-countries",
    "title": "european countries",
    "items": [
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Sweden",
      "Norway",
      "Denmark",
      "Finland",
      "Poland",
      "Austria",
      "Greece",
      "Ireland",
      "Iceland",
      "Romania",
      "Hungary",
      "Croatia",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Estonia",
      "Latvia",
      "Lithuania",
      "Switzerland",
      "Ukraine",
      "Albania",
      "Andorra",
      "Belarus",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Cyprus",
      "Czech Republic",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Montenegro",
      "North Macedonia",
      "San Marino",
      "Kosovo",
      "Liechtenstein",
      "Monaco",
      "Turkey",
      "Vatican City"
    ]
  },
  {
    "id": "us-states",
    "title": "us states",
    "items": [
      "alabama",
      "alaska",
      "arizona",
      "arkansas",
      "california",
      "colorado",
      "connecticut",
      "delaware",
      "florida",
      "georgia",
      "hawaii",
      "idaho",
      "illinois",
      "indiana",
      "iowa",
      "kansas",
      "kentucky",
      "louisiana",
      "maine",
      "maryland",
      "massachusetts",
      "michigan",
      "minnesota",
      "mississippi",
      "missouri",
      "montana",
      "nebraska",
      "nevada",
      "new hampshire",
      "new jersey",
      "new mexico",
      "new york",
      "north carolina",
      "north dakota",
      "ohio",
      "oklahoma",
      "oregon",
      "pennsylvania",
      "rhode island",
      "south carolina",
      "south dakota",
      "tennessee",
      "texas",
      "utah",
      "vermont"
    ]
  },
  {
    "id": "us-cities",
    "title": "us cities",
    "items": [
      "New York City",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Boston",
      "El Paso",
      "Detroit",
      "Nashville",
      "Portland",
      "Memphis",
      "Oklahoma City",
      "Las Vegas",
      "Louisville",
      "Baltimore",
      "Milwaukee",
      "Albuquerque",
      "Tucson",
      "Fresno",
      "Sacramento",
      "Kansas City",
      "Mesa",
      "Atlanta",
      "Omaha",
      "Raleigh",
      "Miami",
      "Oakland",
      "Minneapolis",
      "Tulsa",
      "Cleveland",
      "Wichita",
      "Arlington"
    ]
  },
  {
    "id": "dog-breeds",
    "title": "dog breeds",
    "items": [
      "Labrador Retriever",
      "Golden Retriever",
      "German Shepherd",
      "French Bulldog",
      "Poodle",
      "Beagle",
      "Rottweiler",
      "Dachshund",
      "Siberian Husky",
      "Boxer",
      "Doberman Pinscher",
      "Great Dane",
      "Shih Tzu",
      "Chihuahua",
      "Border Collie",
      "Australian Shepherd",
      "Cocker Spaniel",
      "Boston Terrier",
      "Pug",
      "Mastiff",
      "Saint Bernard",
      "Bichon Frise",
      "Akita",
      "Samoyed",
      "Weimaraner",
      "Newfoundland",
      "Bernese Mountain Dog",
      "Belgian Malinois",
      "Greyhound",
      "Whippet",
      "Papillon",
      "Pomeranian",
      "Bull Terrier",
      "Cane Corso",
      "Shar Pei",
      "Alaskan Malamute",
      "Basenji",
      "Bloodhound",
      "Dalmatian",
      "English Bulldog",
      "Fox Terrier",
      "Irish Setter",
      "Jack Russell Terrier",
      "Vizsla",
      "Yorkshire Terrier"
    ]
  },
  {
    "id": "birds",
    "title": "birds",
    "items": [
      "sparrow",
      "robin",
      "blue jay",
      "cardinal",
      "goldfinch",
      "crow",
      "raven",
      "eagle",
      "hawk",
      "falcon",
      "owl",
      "woodpecker",
      "hummingbird",
      "swallow",
      "starling",
      "wren",
      "warbler",
      "oriole",
      "blackbird",
      "mockingbird",
      "thrush",
      "loon",
      "pelican",
      "heron",
      "egret",
      "flamingo",
      "parrot",
      "macaw",
      "cockatoo",
      "parakeet",
      "pigeon",
      "dove",
      "quail",
      "pheasant",
      "wild turkey",
      "goose",
      "duck",
      "swan",
      "kingfisher",
      "osprey",
      "vulture",
      "condor",
      "kestrel",
      "nuthatch",
      "chickadee"
    ]
  },
  {
    "id": "insects",
    "title": "insects",
    "items": [
      "ant",
      "bee",
      "wasp",
      "hornet",
      "butterfly",
      "moth",
      "beetle",
      "ladybug",
      "dragonfly",
      "damselfly",
      "grasshopper",
      "cricket",
      "locust",
      "mantis",
      "termite",
      "mosquito",
      "gnat",
      "fly",
      "fruit fly",
      "housefly",
      "flea",
      "louse",
      "aphid",
      "cicada",
      "leafhopper",
      "stink bug",
      "firefly",
      "weevil",
      "earwig",
      "silverfish",
      "mayfly",
      "stonefly",
      "caddisfly",
      "lacewing",
      "dobsonfly",
      "walking stick",
      "katydid",
      "cockroach",
      "bark beetle",
      "dung beetle",
      "chafer",
      "blister beetle",
      "sawfly",
      "horsefly",
      "midge"
    ]
  },
  {
    "id": "board-games",
    "title": "board games",
    "items": [
      "Monopoly",
      "Scrabble",
      "Risk",
      "Clue",
      "Catan",
      "Ticket to Ride",
      "Carcassonne",
      "Pandemic",
      "Azul",
      "Splendor",
      "Chess",
      "Checkers",
      "Backgammon",
      "Sorry!",
      "The Game of Life",
      "Yahtzee",
      "Boggle",
      "Battleship",
      "Connect 4",
      "Operation",
      "Guess Who?",
      "Jenga",
      "Twister",
      "Sequence",
      "Dominion",
      "Patchwork",
      "Codenames",
      "Dixit",
      "Hive",
      "Qwirkle",
      "Santorini",
      "7 Wonders",
      "Agricola",
      "Terra Mystica",
      "Wingspan",
      "Scythe",
      "Gloomhaven",
      "Cranium",
      "Pictionary",
      "Taboo",
      "Trivial Pursuit",
      "Mancala",
      "Go",
      "Othello",
      "Mouse Trap"
    ]
  },
  {
    "id": "kitchen-tools",
    "title": "kitchen tools",
    "items": [
      "whisk",
      "spatula",
      "ladle",
      "tongs",
      "colander",
      "grater",
      "peeler",
      "can opener",
      "measuring cup",
      "measuring spoon",
      "cutting board",
      "chef's knife",
      "paring knife",
      "bread knife",
      "rolling pin",
      "mixing bowl",
      "skillet",
      "saucepan",
      "stockpot",
      "sheet pan",
      "baking dish",
      "muffin tin",
      "loaf pan",
      "cooling rack",
      "zester",
      "garlic press",
      "slotted spoon",
      "turner",
      "bench scraper",
      "mortar and pestle",
      "strainer",
      "salad spinner",
      "kettle",
      "fish spatula",
      "spider skimmer",
      "offset spatula",
      "immersion blender",
      "timer",
      "thermometer",
      "pizza cutter",
      "pastry brush",
      "cookie scoop",
      "melon baller",
      "mandoline",
      "sifter"
    ]
  },
  {
    "id": "kitchen-appliances",
    "title": "kitchen appliances",
    "items": [
      "toaster",
      "microwave",
      "blender",
      "food processor",
      "stand mixer",
      "hand mixer",
      "coffee maker",
      "espresso machine",
      "electric kettle",
      "slow cooker",
      "pressure cooker",
      "rice cooker",
      "air fryer",
      "toaster oven",
      "waffle maker",
      "panini press",
      "bread maker",
      "juicer",
      "immersion blender machine",
      "electric griddle",
      "electric skillet",
      "ice cream maker",
      "sous vide machine",
      "hot plate",
      "mini fridge",
      "dishwasher",
      "garbage disposal",
      "electric can opener",
      "milk frother",
      "coffee grinder",
      "meat slicer",
      "vacuum sealer",
      "dehydrator",
      "yogurt maker",
      "popcorn maker",
      "egg cooker",
      "sandwich maker",
      "deep fryer",
      "induction burner",
      "wine cooler",
      "water dispenser",
      "food steamer",
      "warming drawer",
      "ice maker",
      "range hood"
    ]
  },
  {
    "id": "desserts",
    "title": "desserts",
    "items": [
      "brownie",
      "cupcake",
      "donut",
      "eclair",
      "macaron",
      "meringue",
      "trifle",
      "tiramisu",
      "cheesecake",
      "shortcake",
      "pavlova",
      "baklava",
      "cannoli",
      "crepe cake",
      "fruit tart",
      "bread pudding",
      "rice pudding",
      "ice cream cake",
      "lemon bar",
      "blondie",
      "fudge",
      "mousse",
      "sundae",
      "parfait",
      "sorbet",
      "gelato",
      "apple pie",
      "pecan pie",
      "pumpkin pie",
      "banana split",
      "crumble",
      "cobbler",
      "flan",
      "creme brulee",
      "profiterole",
      "opera cake",
      "madeleine",
      "napoleon",
      "biscotti",
      "whoopie pie",
      "snickerdoodle",
      "churro",
      "beignet",
      "semifreddo",
      "poached pear"
    ]
  },
  {
    "id": "cereals",
    "title": "cereals",
    "items": [
      "Cheerios",
      "Corn Flakes",
      "Rice Krispies",
      "Froot Loops",
      "Frosted Flakes",
      "Lucky Charms",
      "Special K",
      "Cocoa Puffs",
      "Trix",
      "Cap'n Crunch",
      "Raisin Bran",
      "Mini-Wheats",
      "Honey Nut Cheerios",
      "Apple Jacks",
      "Cinnamon Toast Crunch",
      "Golden Grahams",
      "Honey Bunches of Oats",
      "Kix",
      "Chex",
      "Cocoa Krispies",
      "Count Chocula",
      "Cookie Crisp",
      "Wheaties",
      "Grape-Nuts",
      "Life",
      "Shredded Wheat",
      "Total",
      "Fruity Pebbles",
      "Cocoa Pebbles",
      "Corn Pops",
      "Cracklin' Oat Bran",
      "Basic 4",
      "Mueslix",
      "Alpha-Bits",
      "Vector",
      "All-Bran",
      "Bran Flakes",
      "Honeycomb",
      "Smart Start",
      "French Toast Crunch",
      "Krave",
      "Berry Berry Kix",
      "Golden Crisp",
      "Malt-O-Meal",
      "Rice Chex"
    ]
  },
  {
    "id": "cheeses",
    "title": "cheeses",
    "items": [
      "cheddar",
      "mozzarella",
      "brie",
      "camembert",
      "gouda",
      "parmesan",
      "pecorino",
      "asiago",
      "provolone",
      "havarti",
      "feta",
      "halloumi",
      "ricotta",
      "mascarpone",
      "stilton",
      "gorgonzola",
      "roquefort",
      "blue cheese",
      "colby",
      "monterey jack",
      "pepper jack",
      "swiss",
      "emmental",
      "gruyere",
      "raclette",
      "fontina",
      "burrata",
      "paneer",
      "cotija",
      "queso fresco",
      "manchego",
      "mimolette",
      "jarlsberg",
      "edam",
      "limburger",
      "comte",
      "taleggio",
      "reblochon",
      "double gloucester",
      "wensleydale",
      "cheshire",
      "caerphilly",
      "red leicester",
      "neufchatel",
      "cantal"
    ]
  },
  {
    "id": "gemstones",
    "title": "gemstones",
    "items": [
      "diamond",
      "ruby",
      "sapphire",
      "emerald",
      "amethyst",
      "topaz",
      "opal",
      "garnet",
      "peridot",
      "aquamarine",
      "tourmaline",
      "citrine",
      "onyx",
      "jade",
      "turquoise",
      "lapis lazuli",
      "moonstone",
      "sunstone",
      "zircon",
      "spinel",
      "tanzanite",
      "iolite",
      "alexandrite",
      "malachite",
      "agate",
      "carnelian",
      "jasper",
      "obsidian",
      "bloodstone",
      "fluorite",
      "amber",
      "coral",
      "pearl",
      "jet",
      "aventurine",
      "chrysoprase",
      "larimar",
      "unakite",
      "serpentine",
      "rhodonite",
      "sodalite",
      "charoite",
      "amazonite",
      "hematite",
      "pyrite"
    ]
  },
  {
    "id": "constellations",
    "title": "constellations",
    "items": [
      "Orion",
      "Ursa Major",
      "Ursa Minor",
      "Cassiopeia",
      "Corona Borealis",
      "Pegasus",
      "Cygnus",
      "Lyra",
      "Aquila",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpius",
      "Sagittarius",
      "Capricornus",
      "Aquarius",
      "Pisces",
      "Aries",
      "Draco",
      "Fornax",
      "Hydra",
      "Centaurus",
      "Crux",
      "Carina",
      "Vela",
      "Puppis",
      "Sagitta",
      "Auriga",
      "Bootes",
      "Canis Major",
      "Canis Minor",
      "Cepheus",
      "Delphinus",
      "Hercules",
      "Lepus",
      "Lupus",
      "Monoceros",
      "Musca",
      "Pavo",
      "Reticulum",
      "Triangulum",
      "Volans"
    ]
  },
  {
    "id": "sci-fi-shows",
    "title": "sci-fi shows",
    "items": [
      "The X-Files",
      "Doctor Who",
      "Black Mirror",
      "Battlestar Galactica",
      "The Twilight Zone",
      "Westworld",
      "Fringe",
      "Lost in Space",
      "The Expanse",
      "Killjoys",
      "Severance",
      "Dark",
      "Foundation",
      "Silo",
      "Andor",
      "Star Trek",
      "Star Trek: Voyager",
      "Star Trek: Discovery",
      "Star Trek: Picard",
      "Raised by Wolves",
      "Orphan Black",
      "Sense8",
      "Heroes",
      "Torchwood",
      "Humans",
      "Altered Carbon",
      "Travelers",
      "Devs",
      "Snowpiercer",
      "Continuum",
      "Farscape",
      "Eureka",
      "Quantum Leap",
      "Caprica",
      "Alien Nation",
      "Resident Alien",
      "Upload",
      "Beacon 23",
      "3 Body Problem",
      "The Peripheral",
      "Babylon 5",
      "Red Dwarf",
      "Lexx",
      "The Last of Us",
      "Halo TV Series"
    ]
  },
  {
    "id": "sitcoms",
    "title": "sitcoms",
    "items": [
      "Friends",
      "The Office",
      "Parks and Recreation",
      "Seinfeld",
      "Frasier",
      "Cheers",
      "Brooklyn Nine-Nine",
      "Modern Family",
      "New Girl",
      "Arrested Development",
      "Community",
      "30 Rock",
      "How I Met Your Mother",
      "Schitt's Creek",
      "Superstore",
      "Abbott Elementary",
      "The Good Place",
      "Black-ish",
      "The Nanny",
      "Will & Grace",
      "Scrubs",
      "Kim's Convenience",
      "Fresh Off the Boat",
      "Everybody Loves Raymond",
      "The Big Bang Theory",
      "That '70s Show",
      "Happy Endings",
      "Cougar Town",
      "Rules of Engagement",
      "Malcolm in the Middle",
      "The Middle",
      "Dharma & Greg",
      "Just Shoot Me!",
      "Wings",
      "Night Court",
      "NewsRadio",
      "Spin City",
      "2 Broke Girls",
      "Bob Hearts Abishola",
      "Reba",
      "Home Improvement",
      "Living Single",
      "Family Matters",
      "Full House",
      "Perfect Strangers"
    ]
  },
  {
    "id": "medical-dramas",
    "title": "medical dramas",
    "items": [
      "ER",
      "Grey's Anatomy",
      "House",
      "The Good Doctor",
      "St. Elsewhere",
      "Chicago Hope",
      "Private Practice",
      "Nurse Jackie",
      "New Amsterdam",
      "Code Black",
      "The Resident",
      "Saving Hope",
      "Transplant",
      "Holby City",
      "Casualty",
      "Call the Midwife",
      "Doc Martin",
      "Mercy",
      "Hawthorne",
      "Three Rivers",
      "Strong Medicine",
      "Trauma",
      "Off the Map",
      "A Gifted Man",
      "Doogie Howser, M.D.",
      "Emily Owens, M.D.",
      "Pure Genius",
      "Nip/Tuck",
      "Body of Proof",
      "Royal Pains",
      "Getting On",
      "Medicine Ball",
      "Heartbeat",
      "The Knick",
      "SkyMed",
      "Bramwell",
      "Dr. Quinn, Medicine Woman",
      "The Night Shift",
      "Lenox Hill",
      "Critical",
      "Monday Mornings",
      "Diagnosis Murder",
      "Hospital Playlist",
      "MASH",
      "Children's Hospital"
    ]
  },
  {
    "id": "movie-titles",
    "title": "movie titles",
    "items": [
      "The Matrix",
      "Inception",
      "Titanic",
      "Avatar",
      "Gladiator",
      "Interstellar",
      "The Godfather",
      "Pulp Fiction",
      "The Dark Knight",
      "Forrest Gump",
      "Casablanca",
      "Jaws",
      "Alien",
      "Rocky",
      "Goodfellas",
      "The Departed",
      "Whiplash",
      "Arrival",
      "Barbie",
      "Oppenheimer",
      "La La Land",
      "Good Will Hunting",
      "Parasite",
      "The Shawshank Redemption",
      "The Silence of the Lambs",
      "Jurassic Park",
      "Back to the Future",
      "The Truman Show",
      "No Country for Old Men",
      "There Will Be Blood",
      "Blade Runner",
      "Top Gun",
      "Toy Story",
      "Finding Nemo",
      "The Lion King",
      "Die Hard",
      "Get Out",
      "Her",
      "The Social Network",
      "Little Women",
      "A Few Good Men",
      "The Prestige",
      "Shrek",
      "Memento",
      "The Grand Budapest Hotel"
    ]
  },
  {
    "id": "song-titles",
    "title": "song titles",
    "items": [
      "Imagine",
      "Firework",
      "Stay",
      "Uptown Funk",
      "Royals",
      "Poker Face",
      "Yellow",
      "Wonderwall",
      "Hey Jude",
      "Purple Rain",
      "Rolling in the Deep",
      "Single Ladies",
      "Shake It Off",
      "Levitating",
      "Viva La Vida",
      "Mr. Brightside",
      "Call Me Maybe",
      "Watermelon Sugar",
      "Take on Me",
      "Dancing Queen",
      "Bohemian Rhapsody",
      "Toxic",
      "Since U Been Gone",
      "Teenage Dream",
      "Blinding Lights",
      "Umbrella",
      "Hello",
      "Dreams",
      "Africa",
      "Creep",
      "Landslide",
      "Jolene",
      "Fast Car",
      "I Will Survive",
      "Respect",
      "Crazy in Love",
      "Hound Dog",
      "Billie Jean",
      "Like a Prayer",
      "Material Girl",
      "As It Was",
      "Flowers",
      "Shallow",
      "Bad Romance",
      "Style"
    ]
  },
  {
    "id": "book-titles",
    "title": "book titles",
    "items": [
      "Pride and Prejudice",
      "Moby-Dick",
      "Jane Eyre",
      "Wuthering Heights",
      "Great Expectations",
      "Middlemarch",
      "The Great Gatsby",
      "To Kill a Mockingbird",
      "Beloved",
      "1984",
      "Brave New World",
      "The Catcher in the Rye",
      "The Grapes of Wrath",
      "Invisible Man",
      "Mrs Dalloway",
      "Rebecca",
      "The Bell Jar",
      "Atonement",
      "Never Let Me Go",
      "The Handmaid's Tale",
      "The Road",
      "White Teeth",
      "The God of Small Things",
      "The Remains of the Day",
      "Midnight's Children",
      "The Secret History",
      "Wolf Hall",
      "The Goldfinch",
      "The Color Purple",
      "Song of Solomon",
      "Their Eyes Were Watching God",
      "Love in the Time of Cholera",
      "One Hundred Years of Solitude",
      "Crime and Punishment",
      "Anna Karenina",
      "The Brothers Karamazov",
      "Madame Bovary",
      "The Name of the Rose",
      "Cloud Atlas",
      "Life of Pi",
      "The Blind Assassin",
      "Normal People",
      "Station Eleven",
      "Lincoln in the Bardo",
      "The Overstory"
    ]
  },
  {
    "id": "break-phrases",
    "title": "break phrases",
    "items": [
      "break away",
      "break bread",
      "break camp",
      "break character",
      "break cover",
      "break down",
      "break even",
      "break free",
      "break ground",
      "break in",
      "break into",
      "break loose",
      "break off",
      "break out",
      "break rank",
      "break silence",
      "break stride",
      "break the bank",
      "break the ice",
      "break the mould",
      "break the news",
      "break the record",
      "break wind",
      "break with tradition",
      "break away from",
      "break from",
      "break through",
      "break up",
      "break with",
      "break bad",
      "break point",
      "break bulk",
      "break journey",
      "break line",
      "break step",
      "breakwater",
      "breakbeat",
      "breakdance",
      "breakfall",
      "breakfront",
      "breakneck",
      "breaktime",
      "breakroom",
      "breakwall",
      "breakbeat culture"
    ]
  },
  {
    "id": "ending-in-light",
    "title": "ending in light",
    "items": [
      "daylight",
      "moonlight",
      "sunlight",
      "starlight",
      "lamplight",
      "candlelight",
      "firelight",
      "gaslight",
      "torchlight",
      "floodlight",
      "spotlight",
      "searchlight",
      "streetlight",
      "stoplight",
      "headlight",
      "taillight",
      "backlight",
      "sidelight",
      "skylight",
      "lowlight",
      "highlight",
      "limelight",
      "footlight",
      "uplight",
      "downlight",
      "penlight",
      "booklight",
      "nightlight",
      "ring light",
      "grow light",
      "pilot light",
      "porch light",
      "fairy light",
      "string light",
      "dome light",
      "courtesy light",
      "map light",
      "reading light",
      "work light",
      "flashlight",
      "blacklight",
      "greenlight",
      "blue light",
      "red light",
      "white light"
    ]
  },
  {
    "id": "musical-instruments",
    "title": "musical instruments",
    "items": [
      "guitar",
      "piano",
      "violin",
      "cello",
      "double bass",
      "harp",
      "flute",
      "clarinet",
      "oboe",
      "bassoon",
      "trumpet",
      "trombone",
      "tuba",
      "French horn",
      "saxophone",
      "drum kit",
      "snare drum",
      "bass drum",
      "xylophone",
      "marimba",
      "tambourine",
      "triangle",
      "cymbals",
      "banjo",
      "mandolin",
      "ukulele",
      "accordion",
      "harmonica",
      "bagpipes",
      "recorder",
      "bass guitar",
      "electric guitar",
      "synthesizer",
      "organ",
      "harpsichord",
      "lute",
      "sitar",
      "tabla",
      "conga",
      "bongo",
      "castanets",
      "dulcimer",
      "piccolo",
      "cor anglais",
      "keytar"
    ]
  }
];
